In [14]:
from numpy import random
import numpy as np
x=random.randint(100,999)
print(x)

619


In [5]:
x=random.randint(100,999,size=(5,3))
print(x)

[[432 534 605]
 [601 784 760]
 [744 106 448]
 [865 580 292]
 [281 545 208]]


In [ ]:
x=random.rand()  # 0 - 1   
print(x)

0.8378786337045458


In [9]:
x=random.rand(5,3)
print(x)

[[0.69622859 0.62372064 0.7970086 ]
 [0.1704975  0.11842533 0.52287468]
 [0.46230659 0.71267487 0.68688458]
 [0.4525004  0.9472709  0.71960646]
 [0.10055048 0.56265669 0.5213751 ]]


In [10]:
x=random.choice([1,2,3,4,5],size=(3,5))
print(x)

[[1 2 5 2 5]
 [3 4 1 3 5]
 [1 2 1 5 1]]


In [12]:
x=random.choice([1,2,3,4,5],p=[0.2,0.2,0.2,0.2,0.2],size=(3,5))
print(x)

[[5 5 1 3 4]
 [5 1 2 1 4]
 [5 4 3 2 2]]


In [17]:
arr=np.array([1,2,3,4,5])
random.shuffle(arr)
arr

array([3, 4, 1, 2, 5])

In [ ]:
arr=np.array([1,2,3,4,5])
print(random.permutation(arr))

In [ ]:
# pip install seaborn


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [21]:
import seaborn as sns
import matplotlib.pyplot as plt
print(sns.get_dataset_names())
sns.load_dataset("iris")

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'dowjones', 'exercise', 'flights', 'fmri', 'geyser', 'glue', 'healthexp', 'iris', 'mpg', 'penguins', 'planets', 'seaice', 'taxis', 'tips', 'titanic']


sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]